version: '3.8'

services:
    backend:
        build:
            context: .
            target: ${DOCKER_TARGET_BACK:-dev}
        image: meu-projeto-backend:latest
        container_name: backend-container
        restart: always
        ports:
            - "${BACK_PORT:-8000}:${BACK_CONTAINER_PORT:-8000}"
        volumes:
            - ${VOLUME_HOST:-.}:/var/www
        env_file:
            - .env
        command: ${BACK_COMMAND:-sh -c "sleep 10 && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"}
        networks:
            - app-network

    db:
        image: mysql:8.0
        container_name: mysql-container
        restart: always
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME:-usuario_placeholder}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        container_name: nginx-backend
        restart: always
        profiles:
            - production
        ports:
            - "${NGINX_BACK_PORT:-8000}:${NGINX_CONTAINER_PORT:-80}"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - backend
        networks:
            - app-network

volumes:
    mysql_data:
    backend_prod_volume:

networks:
    app-network:
        driver: bridge
