name: Deploy Back-end

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: [self-hosted, prod-back]

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login no Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build e Push da Imagem de Produção
      uses: docker/build-push-action@v5
      with:
        context: .
        target: prod
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/meu-projeto-backend:latest

    - name: Atualizar Ambiente e Rodar Migrations
      run: |
        docker pull ${{ secrets.DOCKERHUB_USERNAME }}/meu-projeto-backend:latest
        # Entra na pasta fixa da infraestrutura de produção que criamos no seu Ubuntu Server
        cd ~/app-backend
        # Reinicia apenas o serviço do Laravel aplicando a imagem nova baixada do Docker Hub
        docker compose up -d --force-recreate backend
        # Executa as migrations do banco de dados automaticamente dentro do novo container
        docker exec backend-container php artisan migrate --force
