name: Deploy Back-end Local

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: [self-hosted, prod-back]

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Criar arquivo .env e Executar Build Local
      env:
        DOCKER_TARGET_BACK: prod
        BACK_PORT: 9000
        BACK_CONTAINER_PORT: 9000
        NGINX_BACK_PORT: 8000
        NGINX_CONTAINER_PORT: 80
        BACK_COMMAND: "php-fpm"
        VOLUME_HOST: "./production_code"
      run: |
        echo "APP_ENV=production" > .env
        echo "APP_DEBUG=false" >> .env
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=db" >> .env
        echo "DB_DATABASE=laravel_prod" >> .env
        echo "DB_USERNAME=laravel_user" >> .env
        echo "DB_PASSWORD=senha_segura_producao" >> .env
        echo "DB_ROOT_PASSWORD=senha_root_ultra_segura" >> .env

        # Executa usando o arquivo único tradicional padrão do repositório
        docker compose --profile production down || true
        docker rm -f backend-container mysql-container nginx-backend || true

        docker compose --profile production build --no-cache backend
        docker compose --profile production up -d backend db nginx

        # O Artisan estará lá dentro pronto para ser executado
        sleep 15
        docker exec backend-container php artisan migrate --force
